version: "3"
services:
  vendingmachine:
    image: vendingmachine_image
    ports:
      - "9090:9090"
    networks:
      - vending-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql/mysql-server:8.0
    container_name: vendingmachine_mysqldb
    networks:
      - vending-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=sreevidya
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=vending_machine

networks:
  vending-mysql: 
